import { t, Trans } from "@lingui/macro";
import cx from "classnames";
import { ReactNode, useCallback } from "react";

import {
  BASE_SEPOLIA,
  LOCALHOST,
  ContractsChainId,
  getChainName,
} from "config/chains";
import { getIcon } from "config/icons";
import { useChainId } from "lib/chains";
import { userAnalytics } from "lib/userAnalytics";
import { switchNetwork } from "lib/wallets";
import useWallet from "lib/wallets/useWallet";

import Button from "components/Button/Button";
import { TrackingLink } from "components/TrackingLink/TrackingLink";

import BaseIcon from "img/ic_base_24.svg?react";

const gmxIcon = getIcon("common", "gmx");
const gmIcon = getIcon("common", "gm");
const glvIcon = getIcon("common", "glv");

const NETWORK_ICONS: Record<ContractsChainId, React.ComponentType<{ className?: string }>> = {
  [BASE_SEPOLIA]: BaseIcon,
  [LOCALHOST]: BaseIcon,
};

const BuyLink = ({
  chainId,
  active,
  to,
  network,
  badge,
}: {
  chainId: number;
  active: boolean;
  to: string;
  network: number;
  badge?: ReactNode;
}) => {
  const changeNetwork = useCallback(
    (network) => {
      if (network === chainId) {
        return;
      }
      if (!active) {
        // wait until the internal navigation is done
        setTimeout(() => {
          return switchNetwork(network, active);
        }, 500);
      } else {
        return switchNetwork(network, active);
      }
    },
    [chainId, active]
  );

  const Icon = NETWORK_ICONS[network];

  return (
    <Button to={to} onClick={() => changeNetwork(network)} variant="secondary" className="flex gap-8">
      <Icon className="size-24" />
      <span className="text-typography-primary">{getChainName(network)}</span>
      {badge ? badge : null}
    </Button>
  );
};

function getTrackingLink(link: string) {
  const paramsPrefix = link.includes("?") ? "&" : "?";

  return `${link}${paramsPrefix}${userAnalytics.getSessionForwardParams()}`;
}

export default function BuyCards() {
  const { chainId } = useChainId();
  const { active } = useWallet();

  return (
    <div className="flex w-full flex-col gap-8">
      <BuyCard
        title={<Trans>0xMarkets</Trans>}
        icon={gmxIcon}
        description={
          <Trans>
            0xMarkets is the utility and governance token. It also accrues 30% of the protocol fees via a buyback and
            distribution mechanism.
          </Trans>
        }
        alt="0xMarkets Icons"
        type="buy"
      >
        <div className={cx("flex justify-between max-lg:flex-col max-lg:gap-12")}>
          <div className={cx("buy flex gap-12 max-lg:flex-col")}>
            <BuyLink
              chainId={chainId}
              active={active}
              to={getTrackingLink("/buy_gmx")}
              network={BASE_SEPOLIA}
            />
          </div>
          <TrackingLink>
            <Button
              className="!text-typography-primary"
              newTab
              variant="secondary"
              to="https://docs.0xmarkets.io/docs/category/tokenomics"
            >
              <Trans>Read more</Trans>
            </Button>
          </TrackingLink>
        </div>
      </BuyCard>
      <BuyCard
        title={<Trans>GLV</Trans>}
        icon={glvIcon}
        description={
          <Trans>
            GLV is the liquidity provider token for 0xMarkets vaults. Consist of several GM tokens and accrues fees
            generated by them.
          </Trans>
        }
        alt="GLV icon"
        type="buy"
      >
        <div className={cx("flex justify-between max-lg:flex-col max-lg:gap-12")}>
          <div className={cx("buy flex gap-12 max-lg:flex-col")}>
            <BuyLink
              to={getTrackingLink("/pools?pickBestGlv=1")}
              network={BASE_SEPOLIA}
              chainId={chainId}
              active={active}
            />
          </div>
          <TrackingLink>
            <Button
              className="!text-typography-primary"
              newTab
              variant="secondary"
              to="https://docs.0xmarkets.io/docs/providing-liquidity/v2/#glv-pools"
            >
              <Trans>Read more</Trans>
            </Button>
          </TrackingLink>
        </div>
      </BuyCard>
      <BuyCard
        title={<Trans>GM</Trans>}
        icon={gmIcon}
        description={
          <Trans>
            GM is the liquidity provider token for 0xMarkets markets. Accrues 63% of the markets generated fees.
          </Trans>
        }
        alt="GM icon"
        type="buy"
      >
        <div className={cx("flex justify-between max-lg:flex-col max-lg:gap-12")}>
          <div className={cx("buy flex gap-12 max-lg:flex-col")}>
            <BuyLink
              to={getTrackingLink("/pools")}
              network={BASE_SEPOLIA}
              chainId={chainId}
              active={active}
            />
          </div>
          <TrackingLink>
            <Button
              className="!text-typography-primary"
              newTab
              variant="secondary"
              to="https://docs.0xmarkets.io/docs/providing-liquidity/v2"
            >
              <Trans>Read more</Trans>
            </Button>
          </TrackingLink>
        </div>
      </BuyCard>
    </div>
  );
}

function BuyCard({
  title,
  icon,
  description,
  children,
  alt,
  type,
}: {
  title: ReactNode;
  icon: string | undefined;
  description: ReactNode;
  children: ReactNode;
  alt: string;
  type: "buy" | "sell";
}) {
  return (
    <div className="flex w-full flex-col gap-20 rounded-8 bg-slate-900 p-20">
      <div className="flex flex-col gap-8">
        <div className="flex items-center gap-4">
          <img src={icon} alt={alt} className="size-16" />
          <div className="text-20 font-medium text-typography-primary">{title}</div>
        </div>
        <div className="text-13 text-typography-secondary">{description}</div>
      </div>
      <div className="flex flex-col gap-10">
        <div className="text-caption !text-slate-500">{type === "buy" ? t`Buy token on` : t`Sell token on`}</div>
        {children}
      </div>
    </div>
  );
}
